name: Check Repository Updates

on:
  schedule:
    - cron: '0 0 * * *' # 每30分钟运行一次
  workflow_dispatch: # 手动触发

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      # 确保检出整个仓库历史
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完整检出仓库，包括所有提交历史

      # 获取目标仓库最新的提交信息
      - name: Check for Updates
        id: check_updates
        run: |
          # 目标仓库的所有者和名称
          REPO_OWNER="QiuSimons"
          REPO_NAME="luci-app-daed"

          # 获取上一次检查时的最新提交哈希值
          if [ -f last_commit.txt ]; then
            LAST_COMMIT=$(cat last_commit.txt)
          else
            LAST_COMMIT=""
          fi

          # 通过 GitHub API 获取最新的提交哈希值
          NEW_COMMIT=$(curl -s "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/commits?per_page=1" | jq -r '.[0].sha')

          echo "Last commit: $LAST_COMMIT"
          echo "New commit: $NEW_COMMIT"

          # 如果有新提交，更新记录并将结果写入环境文件
          if [ "$NEW_COMMIT" != "$LAST_COMMIT" ]; then
            echo "Repository has been updated."
            echo "$NEW_COMMIT" > last_commit.txt
            echo "repo_updated=true" >> $GITHUB_ENV
          else
            echo "No updates found."
            echo "repo_updated=false" >> $GITHUB_ENV
          fi

      # 提交更新的 last_commit.txt 文件到 GitHub 仓库
      - name: Commit last commit hash
        if: env.repo_updated == 'true'
        run: |
          git config --global user.email "${{ vars.USER_EMAIL }}"
          git config --global user.name "GitHub Actions"
          git add last_commit.txt
          git commit -m "Update last commit hash"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # 触发另一个工作流（工作流 B）
      - name: Trigger X86-OpenWrt if repository has updates
        if: env.repo_updated == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workb.yml/dispatches \
            -d '{"ref":"23.05"}'
