name: Cleaning

on:
  schedule:
    - cron: 1 1 * * 1
  watch:
    types: started

jobs:
  
  Cleanup-Old-Releases:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:  
    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 9
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKENS }}

  Cleanup-Old-Artifacts:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Cleanup Old Action Artifacts
      uses: heidi-pay/gha-delete-artifacts@main
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKENS }}
      with:
        days: 3
        max-artifacts-to-delete: 100
        dry-run: no
        
  Cleanup-Workflow-Logs:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.WORKFLOW_TOKENS }}
          repository: ${{ github.repository }}
          retain_days: 3
